// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type BatchReplayEventsRequest struct {
	// Batch replay request payload
	BatchReplayRequest shared.BatchReplayRequest `request:"mediaType=application/json"`
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
}

func (b *BatchReplayEventsRequest) GetBatchReplayRequest() shared.BatchReplayRequest {
	if b == nil {
		return shared.BatchReplayRequest{}
	}
	return b.BatchReplayRequest
}

func (b *BatchReplayEventsRequest) GetConfigID() string {
	if b == nil {
		return ""
	}
	return b.ConfigID
}

// BatchReplayEventsResponseBody - Success - enqueued events for replay
type BatchReplayEventsResponseBody struct {
	// List of event ids that were enqueued for replay
	ReplayedEventIds []string `json:"replayed_event_ids,omitempty"`
}

func (b *BatchReplayEventsResponseBody) GetReplayedEventIds() []string {
	if b == nil {
		return nil
	}
	return b.ReplayedEventIds
}

type BatchReplayEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - enqueued events for replay
	Object *BatchReplayEventsResponseBody
}

func (b *BatchReplayEventsResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BatchReplayEventsResponse) GetErrorResp() *shared.ErrorResp {
	if b == nil {
		return nil
	}
	return b.ErrorResp
}

func (b *BatchReplayEventsResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BatchReplayEventsResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BatchReplayEventsResponse) GetObject() *BatchReplayEventsResponseBody {
	if b == nil {
		return nil
	}
	return b.Object
}
