// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ResponseBody struct {
	DownloadURL  *string `json:"download_url,omitempty"`
	FileEntityID *string `json:"file_entity_id,omitempty"`
}

func (o *ResponseBody) GetDownloadURL() *string {
	if o == nil {
		return nil
	}
	return o.DownloadURL
}

func (o *ResponseBody) GetFileEntityID() *string {
	if o == nil {
		return nil
	}
	return o.FileEntityID
}

type DownloadFilesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Generated download urls
	Classes []ResponseBody
}

func (o *DownloadFilesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DownloadFilesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DownloadFilesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DownloadFilesResponse) GetClasses() []ResponseBody {
	if o == nil {
		return nil
	}
	return o.Classes
}
