// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetConfigRequest struct {
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
}

func (g *GetConfigRequest) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

type GetConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// No configuration found for this id
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - if the config is updated successfully
	WebhookConfig *shared.WebhookConfig
}

func (g *GetConfigResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetConfigResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetConfigResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetConfigResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetConfigResponse) GetWebhookConfig() *shared.WebhookConfig {
	if g == nil {
		return nil
	}
	return g.WebhookConfig
}
