// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetConfigsRequest struct {
	// Filter configurations by event Name
	EventName *string `queryParam:"style=form,explode=true,name=eventName"`
}

func (o *GetConfigsRequest) GetEventName() *string {
	if o == nil {
		return nil
	}
	return o.EventName
}

type GetConfigsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Other errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - configs loaded with success. Empty array if org has configs.
	Classes []shared.WebhookConfig
}

func (o *GetConfigsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetConfigsResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetConfigsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetConfigsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetConfigsResponse) GetClasses() []shared.WebhookConfig {
	if o == nil {
		return nil
	}
	return o.Classes
}
