// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetConfiguredEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Success - configured events loaded with success. Empty array if no events have been configured.
	EventConfigResp []shared.EventConfigEntry
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetConfiguredEventsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetConfiguredEventsResponse) GetEventConfigResp() []shared.EventConfigEntry {
	if o == nil {
		return nil
	}
	return o.EventConfigResp
}

func (o *GetConfiguredEventsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetConfiguredEventsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
