// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetEventByIDRequest struct {
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
	// Event id
	EventID string `pathParam:"style=simple,explode=false,name=eventId"`
}

func (g *GetEventByIDRequest) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

func (g *GetEventByIDRequest) GetEventID() string {
	if g == nil {
		return ""
	}
	return g.EventID
}

type GetEventByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// No events found
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - event
	WebhookEvent *shared.WebhookEvent
}

func (g *GetEventByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEventByIDResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetEventByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEventByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEventByIDResponse) GetWebhookEvent() *shared.WebhookEvent {
	if g == nil {
		return nil
	}
	return g.WebhookEvent
}
