// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetFailuresRequest struct {
	// Optional Key. To be provided when loading paginated data. It is always returned initially by this API, is pagination is needed.
	LastLoadedEventID *string `queryParam:"style=form,explode=true,name=lastLoadedEventId"`
	// Optional Key. To be provided when loading paginated data. It is always returned initially by this API, is pagination is needed.
	LastLoadedTimestamp *string `queryParam:"style=form,explode=true,name=lastLoadedTimestamp"`
}

func (o *GetFailuresRequest) GetLastLoadedEventID() *string {
	if o == nil {
		return nil
	}
	return o.LastLoadedEventID
}

func (o *GetFailuresRequest) GetLastLoadedTimestamp() *string {
	if o == nil {
		return nil
	}
	return o.LastLoadedTimestamp
}

type GetFailuresResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// Success - if the API call returned successfully
	FailuresResp *shared.FailuresResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetFailuresResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFailuresResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetFailuresResponse) GetFailuresResp() *shared.FailuresResp {
	if o == nil {
		return nil
	}
	return o.FailuresResp
}

func (o *GetFailuresResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFailuresResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
