// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetFailuresForConfigRequest struct {
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
	// Optional Key. To be provided when loading paginated data. It is always returned initially by this API, if pagination is needed.
	LastLoadedEventID   *string `queryParam:"style=form,explode=true,name=lastLoadedEventId"`
	LastLoadedTimestamp *string `queryParam:"style=form,explode=true,name=lastLoadedTimestamp"`
}

func (g *GetFailuresForConfigRequest) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

func (g *GetFailuresForConfigRequest) GetLastLoadedEventID() *string {
	if g == nil {
		return nil
	}
	return g.LastLoadedEventID
}

func (g *GetFailuresForConfigRequest) GetLastLoadedTimestamp() *string {
	if g == nil {
		return nil
	}
	return g.LastLoadedTimestamp
}

type GetFailuresForConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// No configuration found for this id
	ErrorResp *shared.ErrorResp
	// Success
	FailuresResp *shared.FailuresResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetFailuresForConfigResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFailuresForConfigResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetFailuresForConfigResponse) GetFailuresResp() *shared.FailuresResp {
	if g == nil {
		return nil
	}
	return g.FailuresResp
}

func (g *GetFailuresForConfigResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFailuresForConfigResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
