// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetPublicKeyRequest struct {
	// Organization ID to retrieve the public key for.
	OrgID string `queryParam:"style=form,explode=true,name=orgId"`
}

func (g *GetPublicKeyRequest) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}

type GetPublicKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Internal server error
	ErrorResp *shared.ErrorResp
	// Success - public key returned
	PublicKeyResponse *shared.PublicKeyResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetPublicKeyResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPublicKeyResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetPublicKeyResponse) GetPublicKeyResponse() *shared.PublicKeyResponse {
	if g == nil {
		return nil
	}
	return g.PublicKeyResponse
}

func (g *GetPublicKeyResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPublicKeyResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
