// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type GetWebhookEventsV2Request struct {
	SearchOptions *shared.SearchOptions `request:"mediaType=application/json"`
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
}

func (g *GetWebhookEventsV2Request) GetSearchOptions() *shared.SearchOptions {
	if g == nil {
		return nil
	}
	return g.SearchOptions
}

func (g *GetWebhookEventsV2Request) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

type GetWebhookEventsV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Success - events where loaded successfully. Empty array if org has no events.
	EventListResponse *shared.EventListResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetWebhookEventsV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWebhookEventsV2Response) GetEventListResponse() *shared.EventListResponse {
	if g == nil {
		return nil
	}
	return g.EventListResponse
}

func (g *GetWebhookEventsV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWebhookEventsV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
