// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

// Status - Get all events for a given webhook config id
type Status string

const (
	StatusSucceeded  Status = "succeeded"
	StatusFailed     Status = "failed"
	StatusInProgress Status = "in_progress"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "in_progress":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type GetWehookEventsRequest struct {
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
	// Base64 encoded cursor to be used for pagination
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Get all events for a given webhook config id
	Status *Status `queryParam:"style=form,explode=true,name=status"`
}

func (g *GetWehookEventsRequest) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

func (g *GetWehookEventsRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetWehookEventsRequest) GetStatus() *Status {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetWehookEventsResponseBody - Success - list events
type GetWehookEventsResponseBody struct {
	// Cursor to be used for pagination
	Cursor *string               `json:"cursor,omitempty"`
	Data   []shared.WebhookEvent `json:"data,omitempty"`
}

func (g *GetWehookEventsResponseBody) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetWehookEventsResponseBody) GetData() []shared.WebhookEvent {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetWehookEventsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// No events found
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - list events
	Object *GetWehookEventsResponseBody
}

func (g *GetWehookEventsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWehookEventsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetWehookEventsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWehookEventsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetWehookEventsResponse) GetObject() *GetWehookEventsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
