// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
	"net/http"
)

type PreviewFileRequest struct {
	// height
	H  *int64 `queryParam:"style=form,explode=true,name=h"`
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// index of file version
	Version *int64 `default:"0" queryParam:"style=form,explode=true,name=version"`
	// width
	W *int64 `queryParam:"style=form,explode=true,name=w"`
}

func (p PreviewFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PreviewFileRequest) GetH() *int64 {
	if o == nil {
		return nil
	}
	return o.H
}

func (o *PreviewFileRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PreviewFileRequest) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *PreviewFileRequest) GetW() *int64 {
	if o == nil {
		return nil
	}
	return o.W
}

type PreviewFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PreviewFileResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PreviewFileResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PreviewFileResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
