// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type ReplayEventRequest struct {
	// Short uuid to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
	// Event id
	EventID string `pathParam:"style=simple,explode=false,name=eventId"`
}

func (r *ReplayEventRequest) GetConfigID() string {
	if r == nil {
		return ""
	}
	return r.ConfigID
}

func (r *ReplayEventRequest) GetEventID() string {
	if r == nil {
		return ""
	}
	return r.EventID
}

type ReplayEventResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// No events found
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *ReplayEventResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReplayEventResponse) GetErrorResp() *shared.ErrorResp {
	if r == nil {
		return nil
	}
	return r.ErrorResp
}

func (r *ReplayEventResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReplayEventResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
