// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"net/http"
)

type UpdateConfigRequest struct {
	// Webhook config payload
	WebhookConfig shared.WebhookConfigInput `request:"mediaType=application/json"`
	// Short uuid (length 6) to identify the webhook configuration.
	ConfigID string `pathParam:"style=simple,explode=false,name=configId"`
}

func (u *UpdateConfigRequest) GetWebhookConfig() shared.WebhookConfigInput {
	if u == nil {
		return shared.WebhookConfigInput{}
	}
	return u.WebhookConfig
}

func (u *UpdateConfigRequest) GetConfigID() string {
	if u == nil {
		return ""
	}
	return u.ConfigID
}

type UpdateConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success - if the config is updated successfully
	WebhookConfig *shared.WebhookConfig
}

func (u *UpdateConfigResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateConfigResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UpdateConfigResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateConfigResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateConfigResponse) GetWebhookConfig() *shared.WebhookConfig {
	if u == nil {
		return nil
	}
	return u.WebhookConfig
}
