// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// APIKeyConfig - To be sent only if authType is API_KEY
type APIKeyConfig struct {
	KeyName  string  `json:"keyName"`
	KeyValue *string `json:"keyValue,omitempty"`
	// When true, indicates the keyValue is an environment variable reference (e.g. {{ env.my_secret }})
	KeyValueIsEnvVar *bool `json:"keyValueIsEnvVar,omitempty"`
}

func (a *APIKeyConfig) GetKeyName() string {
	if a == nil {
		return ""
	}
	return a.KeyName
}

func (a *APIKeyConfig) GetKeyValue() *string {
	if a == nil {
		return nil
	}
	return a.KeyValue
}

func (a *APIKeyConfig) GetKeyValueIsEnvVar() *bool {
	if a == nil {
		return nil
	}
	return a.KeyValueIsEnvVar
}
