// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// APIKeyConfig - To be sent only if authType is API_KEY
type APIKeyConfig struct {
	KeyName  string  `json:"keyName"`
	KeyValue *string `json:"keyValue,omitempty"`
}

func (o *APIKeyConfig) GetKeyName() string {
	if o == nil {
		return ""
	}
	return o.KeyName
}

func (o *APIKeyConfig) GetKeyValue() *string {
	if o == nil {
		return nil
	}
	return o.KeyValue
}
