// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Auth struct {
	// To be sent only if authType is API_KEY
	APIKeyConfig *APIKeyConfig `json:"apiKeyConfig,omitempty"`
	AuthType     AuthType      `json:"authType"`
	// To be sent only if authType is BASIC
	BasicAuthConfig *BasicAuthConfig `json:"basicAuthConfig,omitempty"`
	// To be sent only if authType is OAUTH_CLIENT_CREDENTIALS
	OauthConfig *OAuthConfig `json:"oauthConfig,omitempty"`
}

func (o *Auth) GetAPIKeyConfig() *APIKeyConfig {
	if o == nil {
		return nil
	}
	return o.APIKeyConfig
}

func (o *Auth) GetAuthType() AuthType {
	if o == nil {
		return AuthType("")
	}
	return o.AuthType
}

func (o *Auth) GetBasicAuthConfig() *BasicAuthConfig {
	if o == nil {
		return nil
	}
	return o.BasicAuthConfig
}

func (o *Auth) GetOauthConfig() *OAuthConfig {
	if o == nil {
		return nil
	}
	return o.OauthConfig
}
