// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AuthType string

const (
	AuthTypeBasic                  AuthType = "BASIC"
	AuthTypeOauthClientCredentials AuthType = "OAUTH_CLIENT_CREDENTIALS"
	AuthTypeAPIKey                 AuthType = "API_KEY"
	AuthTypeNone                   AuthType = "NONE"
)

func (e AuthType) ToPointer() *AuthType {
	return &e
}
func (e *AuthType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BASIC":
		fallthrough
	case "OAUTH_CLIENT_CREDENTIALS":
		fallthrough
	case "API_KEY":
		fallthrough
	case "NONE":
		*e = AuthType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthType: %v", v)
	}
}
