// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// BasicAuthConfig - To be sent only if authType is BASIC
type BasicAuthConfig struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

func (b *BasicAuthConfig) GetPassword() *string {
	if b == nil {
		return nil
	}
	return b.Password
}

func (b *BasicAuthConfig) GetUsername() string {
	if b == nil {
		return ""
	}
	return b.Username
}
