// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// BasicAuthConfig - To be sent only if authType is BASIC
type BasicAuthConfig struct {
	Password *string `json:"password,omitempty"`
	Username string  `json:"username"`
}

func (o *BasicAuthConfig) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *BasicAuthConfig) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
