// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BatchReplayRequest struct {
	// List of event IDs to replay
	EventIds []string `json:"eventIds"`
}

func (b *BatchReplayRequest) GetEventIds() []string {
	if b == nil {
		return []string{}
	}
	return b.EventIds
}
