// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// DeliveryMode - Controls how file data is delivered to the endpoint. Only relevant when the webhook is triggered by a file event. Absent for non-file-event webhooks.
type DeliveryMode string

const (
	DeliveryModeJSONBase64      DeliveryMode = "json_base64"
	DeliveryModeBinaryMultipart DeliveryMode = "binary_multipart"
)

func (e DeliveryMode) ToPointer() *DeliveryMode {
	return &e
}
func (e *DeliveryMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json_base64":
		fallthrough
	case "binary_multipart":
		*e = DeliveryMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeliveryMode: %v", v)
	}
}
