// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EventConfigEntry struct {
	// Either a user friendly label, or the eventName itself.
	EventLabel *string `json:"eventLabel,omitempty"`
	// Name for identifying the event. Unique.
	EventName *string `json:"eventName,omitempty"`
}

func (e *EventConfigEntry) GetEventLabel() *string {
	if e == nil {
		return nil
	}
	return e.EventLabel
}

func (e *EventConfigEntry) GetEventName() *string {
	if e == nil {
		return nil
	}
	return e.EventName
}
