// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
	"time"
)

// NextCursor - Cursor to fetch the next page. Null if no more results.
type NextCursor struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	EventID   *string    `json:"event_id,omitempty"`
}

func (n NextCursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NextCursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NextCursor) GetCreatedAt() *time.Time {
	if n == nil {
		return nil
	}
	return n.CreatedAt
}

func (n *NextCursor) GetEventID() *string {
	if n == nil {
		return nil
	}
	return n.EventID
}

type EventListResponse struct {
	// List of webhook events
	Data []WebhookEvent `json:"data,omitempty"`
	// Indicates if more results are available
	HasMore *bool `json:"has_more,omitempty"`
	// Cursor to fetch the next page. Null if no more results.
	NextCursor *NextCursor `json:"next_cursor,omitempty"`
}

func (e *EventListResponse) GetData() []WebhookEvent {
	if e == nil {
		return nil
	}
	return e.Data
}

func (e *EventListResponse) GetHasMore() *bool {
	if e == nil {
		return nil
	}
	return e.HasMore
}

func (e *EventListResponse) GetNextCursor() *NextCursor {
	if e == nil {
		return nil
	}
	return e.NextCursor
}
