// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
)

type ExampleResponse struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Example payload for the webhook event
	Entity map[string]any `json:"entity,omitempty"`
	// Contains the metadata about the configured event
	Metadata *Metadata `json:"metadata,omitempty"`
	// Example relations for the webhook event
	Relations []map[string]any `json:"relations,omitempty"`
}

func (e ExampleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExampleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExampleResponse) GetAdditionalProperties() any {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *ExampleResponse) GetEntity() map[string]any {
	if e == nil {
		return nil
	}
	return e.Entity
}

func (e *ExampleResponse) GetMetadata() *Metadata {
	if e == nil {
		return nil
	}
	return e.Metadata
}

func (e *ExampleResponse) GetRelations() []map[string]any {
	if e == nil {
		return nil
	}
	return e.Relations
}
