// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ExampleRequest struct {
	// ID of the automation, if applicable
	AutomationID *string `json:"automation_id,omitempty"`
}

func (e *ExampleRequest) GetAutomationID() *string {
	if e == nil {
		return nil
	}
	return e.AutomationID
}
