// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ExecutionPayload - Payload for triggering a webhook
type ExecutionPayload struct {
	// Contains the metadata about the configured event
	Metadata Metadata `json:"metadata"`
}

func (o *ExecutionPayload) GetMetadata() Metadata {
	if o == nil {
		return Metadata{}
	}
	return o.Metadata
}
