// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ExecutionPayload - Payload for triggering a webhook
type ExecutionPayload struct {
	// Contains the metadata about the configured event
	Metadata Metadata `json:"metadata"`
}

func (e *ExecutionPayload) GetMetadata() Metadata {
	if e == nil {
		return Metadata{}
	}
	return e.Metadata
}
