// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FailuresResp - Response for get errors request.
type FailuresResp struct {
	Failures []FailureEntry `json:"failures"`
	// Key of last loaded item previously returned via paginated response
	LastLoadedKey *FailureLastKey `json:"lastLoadedKey,omitempty"`
}

func (o *FailuresResp) GetFailures() []FailureEntry {
	if o == nil {
		return []FailureEntry{}
	}
	return o.Failures
}

func (o *FailuresResp) GetLastLoadedKey() *FailureLastKey {
	if o == nil {
		return nil
	}
	return o.LastLoadedKey
}
