// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FailureLastKey - Key of last loaded item previously returned via paginated response
type FailureLastKey struct {
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	EventID           *string `json:"eventId,omitempty"`
	OrgID             *string `json:"orgId,omitempty"`
	WebhookConfigID   *string `json:"webhookConfigId,omitempty"`
}

func (f *FailureLastKey) GetCreationTimestamp() *string {
	if f == nil {
		return nil
	}
	return f.CreationTimestamp
}

func (f *FailureLastKey) GetEventID() *string {
	if f == nil {
		return nil
	}
	return f.EventID
}

func (f *FailureLastKey) GetOrgID() *string {
	if f == nil {
		return nil
	}
	return f.OrgID
}

func (f *FailureLastKey) GetWebhookConfigID() *string {
	if f == nil {
		return nil
	}
	return f.WebhookConfigID
}
