// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// FailureLastKey - Key of last loaded item previously returned via paginated response
type FailureLastKey struct {
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	EventID           *string `json:"eventId,omitempty"`
	OrgID             *string `json:"orgId,omitempty"`
	WebhookConfigID   *string `json:"webhookConfigId,omitempty"`
}

func (o *FailureLastKey) GetCreationTimestamp() *string {
	if o == nil {
		return nil
	}
	return o.CreationTimestamp
}

func (o *FailureLastKey) GetEventID() *string {
	if o == nil {
		return nil
	}
	return o.EventID
}

func (o *FailureLastKey) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *FailureLastKey) GetWebhookConfigID() *string {
	if o == nil {
		return nil
	}
	return o.WebhookConfigID
}
