// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FileItem struct {
	Filename     *string `json:"filename,omitempty"`
	MimeType     *string `json:"mime_type,omitempty"`
	ReadableSize *string `json:"readable_size,omitempty"`
	S3ref        *S3Ref  `json:"s3ref,omitempty"`
	SizeBytes    *int64  `json:"size_bytes,omitempty"`
}

func (o *FileItem) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *FileItem) GetMimeType() *string {
	if o == nil {
		return nil
	}
	return o.MimeType
}

func (o *FileItem) GetReadableSize() *string {
	if o == nil {
		return nil
	}
	return o.ReadableSize
}

func (o *FileItem) GetS3ref() *S3Ref {
	if o == nil {
		return nil
	}
	return o.S3ref
}

func (o *FileItem) GetSizeBytes() *int64 {
	if o == nil {
		return nil
	}
	return o.SizeBytes
}
