// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FileRelationItem struct {
	// URL-friendly identifier for the entity schema
	Schema   *string  `json:"_schema,omitempty"`
	Tags     []string `json:"_tags,omitempty"`
	EntityID string   `json:"entity_id"`
}

func (o *FileRelationItem) GetSchema() *string {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *FileRelationItem) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *FileRelationItem) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}
