// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FileType string

const (
	FileTypeDocument         FileType = "document"
	FileTypeDocumentTemplate FileType = "document_template"
	FileTypeText             FileType = "text"
	FileTypeImage            FileType = "image"
	FileTypeVideo            FileType = "video"
	FileTypeAudio            FileType = "audio"
	FileTypeSpreadsheet      FileType = "spreadsheet"
	FileTypePresentation     FileType = "presentation"
	FileTypeFont             FileType = "font"
	FileTypeArchive          FileType = "archive"
	FileTypeApplication      FileType = "application"
	FileTypeUnknown          FileType = "unknown"
)

func (e FileType) ToPointer() *FileType {
	return &e
}
func (e *FileType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "document":
		fallthrough
	case "document_template":
		fallthrough
	case "text":
		fallthrough
	case "image":
		fallthrough
	case "video":
		fallthrough
	case "audio":
		fallthrough
	case "spreadsheet":
		fallthrough
	case "presentation":
		fallthrough
	case "font":
		fallthrough
	case "archive":
		fallthrough
	case "application":
		fallthrough
	case "unknown":
		*e = FileType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FileType: %v", v)
	}
}
