// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Filter struct {
	KeyToFilter     string   `json:"keyToFilter"`
	SupportedValues []string `json:"supportedValues"`
}

func (f *Filter) GetKeyToFilter() string {
	if f == nil {
		return ""
	}
	return f.KeyToFilter
}

func (f *Filter) GetSupportedValues() []string {
	if f == nil {
		return []string{}
	}
	return f.SupportedValues
}
