// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// MultipartConfig - Configuration for binary_multipart delivery mode. Specifies the field names used in the multipart form data request.
type MultipartConfig struct {
	// The name of the form field containing the file binary data.
	FileFieldName *string `json:"fileFieldName,omitempty"`
	// The name of the form field containing the JSON metadata payload.
	MetadataFieldName *string `json:"metadataFieldName,omitempty"`
}

func (m *MultipartConfig) GetFileFieldName() *string {
	if m == nil {
		return nil
	}
	return m.FileFieldName
}

func (m *MultipartConfig) GetMetadataFieldName() *string {
	if m == nil {
		return nil
	}
	return m.MetadataFieldName
}
