// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// OAuthConfig - To be sent only if authType is OAUTH_CLIENT_CREDENTIALS
type OAuthConfig struct {
	ClientID     string  `json:"clientId"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	// When true, indicates the clientSecret value is an environment variable reference (e.g. {{ env.my_secret }})
	ClientSecretIsEnvVar *bool                  `json:"clientSecretIsEnvVar,omitempty"`
	CustomParameterList  []CustomOAuthParameter `json:"customParameterList,omitempty"`
	// Https Endpoint for authentication
	Endpoint   string     `json:"endpoint"`
	HTTPMethod HTTPMethod `json:"httpMethod"`
}

func (o *OAuthConfig) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *OAuthConfig) GetClientSecret() *string {
	if o == nil {
		return nil
	}
	return o.ClientSecret
}

func (o *OAuthConfig) GetClientSecretIsEnvVar() *bool {
	if o == nil {
		return nil
	}
	return o.ClientSecretIsEnvVar
}

func (o *OAuthConfig) GetCustomParameterList() []CustomOAuthParameter {
	if o == nil {
		return nil
	}
	return o.CustomParameterList
}

func (o *OAuthConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *OAuthConfig) GetHTTPMethod() HTTPMethod {
	if o == nil {
		return HTTPMethod("")
	}
	return o.HTTPMethod
}
