// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PayloadConfiguration - Configuration for the webhook payload
type PayloadConfiguration struct {
	// Object representing custom headers as key-value pairs.
	CustomHeaders            map[string]string `json:"custom_headers,omitempty"`
	HydrateEntity            *bool             `json:"hydrate_entity,omitempty"`
	IncludeActivity          *bool             `json:"include_activity,omitempty"`
	IncludeChangedAttributes *bool             `json:"include_changed_attributes,omitempty"`
	IncludeRelations         *bool             `json:"include_relations,omitempty"`
}

func (p *PayloadConfiguration) GetCustomHeaders() map[string]string {
	if p == nil {
		return nil
	}
	return p.CustomHeaders
}

func (p *PayloadConfiguration) GetHydrateEntity() *bool {
	if p == nil {
		return nil
	}
	return p.HydrateEntity
}

func (p *PayloadConfiguration) GetIncludeActivity() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeActivity
}

func (p *PayloadConfiguration) GetIncludeChangedAttributes() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeChangedAttributes
}

func (p *PayloadConfiguration) GetIncludeRelations() *bool {
	if p == nil {
		return nil
	}
	return p.IncludeRelations
}
