// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublicKeyResponse struct {
	// The signing algorithm used
	Algorithm string `json:"algorithm"`
	// The issuer of the signing key
	Issuer *string `json:"issuer,omitempty"`
	// PEM-encoded Ed25519 public key for verifying webhook signatures
	PublicKey string `json:"public_key"`
}

func (p *PublicKeyResponse) GetAlgorithm() string {
	if p == nil {
		return ""
	}
	return p.Algorithm
}

func (p *PublicKeyResponse) GetIssuer() *string {
	if p == nil {
		return nil
	}
	return p.Issuer
}

func (p *PublicKeyResponse) GetPublicKey() string {
	if p == nil {
		return ""
	}
	return p.PublicKey
}
