// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublicLink struct {
	// ID of the public link
	ID *string `json:"id,omitempty"`
	// The most recent timestamp when the file was accessed
	LastAccessedAt *string `json:"last_accessed_at,omitempty"`
	// Public link of the file
	Link *string `json:"link,omitempty"`
}

func (o *PublicLink) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PublicLink) GetLastAccessedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastAccessedAt
}

func (o *PublicLink) GetLink() *string {
	if o == nil {
		return nil
	}
	return o.Link
}
