// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
)

type SaveS3FilePayloadAccessControl string

const (
	SaveS3FilePayloadAccessControlPrivate    SaveS3FilePayloadAccessControl = "private"
	SaveS3FilePayloadAccessControlPublicRead SaveS3FilePayloadAccessControl = "public-read"
)

func (e SaveS3FilePayloadAccessControl) ToPointer() *SaveS3FilePayloadAccessControl {
	return &e
}
func (e *SaveS3FilePayloadAccessControl) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public-read":
		*e = SaveS3FilePayloadAccessControl(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SaveS3FilePayloadAccessControl: %v", v)
	}
}

type SaveS3FilePayload struct {
	AdditionalProperties any                             `additionalProperties:"true" json:"-"`
	ID                   *string                         `json:"_id,omitempty"`
	Purpose              []string                        `json:"_purpose,omitempty"`
	Tags                 []string                        `json:"_tags,omitempty"`
	AccessControl        *SaveS3FilePayloadAccessControl `default:"private" json:"access_control"`
	// Custom external download url used for the file
	CustomDownloadURL *string `json:"custom_download_url,omitempty"`
	// Deprecated, use _id instead
	//
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	FileEntityID *string `json:"file_entity_id,omitempty"`
	Filename     *string `json:"filename,omitempty"`
	// MIME type of the file
	MimeType *string `json:"mime_type,omitempty"`
	// List of entities to relate the file to
	Relations []FileRelationItem `json:"relations,omitempty"`
	S3ref     *S3Ref             `json:"s3ref,omitempty"`
	Type      *FileType          `json:"type,omitempty"`
}

func (s SaveS3FilePayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SaveS3FilePayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *SaveS3FilePayload) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *SaveS3FilePayload) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SaveS3FilePayload) GetPurpose() []string {
	if o == nil {
		return nil
	}
	return o.Purpose
}

func (o *SaveS3FilePayload) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *SaveS3FilePayload) GetAccessControl() *SaveS3FilePayloadAccessControl {
	if o == nil {
		return nil
	}
	return o.AccessControl
}

func (o *SaveS3FilePayload) GetCustomDownloadURL() *string {
	if o == nil {
		return nil
	}
	return o.CustomDownloadURL
}

func (o *SaveS3FilePayload) GetFileEntityID() *string {
	if o == nil {
		return nil
	}
	return o.FileEntityID
}

func (o *SaveS3FilePayload) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *SaveS3FilePayload) GetMimeType() *string {
	if o == nil {
		return nil
	}
	return o.MimeType
}

func (o *SaveS3FilePayload) GetRelations() []FileRelationItem {
	if o == nil {
		return nil
	}
	return o.Relations
}

func (o *SaveS3FilePayload) GetS3ref() *S3Ref {
	if o == nil {
		return nil
	}
	return o.S3ref
}

func (o *SaveS3FilePayload) GetType() *FileType {
	if o == nil {
		return nil
	}
	return o.Type
}
