// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
	"time"
)

// Cursor for pagination. Use the next_cursor from the previous response to get the next page.
type Cursor struct {
	// Timestamp from the last event in the previous page
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Event ID from the last event in the previous page
	EventID *string `json:"event_id,omitempty"`
}

func (c Cursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Cursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Cursor) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Cursor) GetEventID() *string {
	if c == nil {
		return nil
	}
	return c.EventID
}

// Status - Filter by event outcome
type Status string

const (
	StatusSucceeded Status = "succeeded"
	StatusFailed    Status = "failed"
	StatusSkipped   Status = "skipped"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "skipped":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// Timestamp - Filter events by timestamp range
type Timestamp struct {
	// Start timestamp in ISO 8601 format
	From *time.Time `json:"from,omitempty"`
	// End timestamp in ISO 8601 format
	To *time.Time `json:"to,omitempty"`
}

func (t Timestamp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Timestamp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Timestamp) GetFrom() *time.Time {
	if t == nil {
		return nil
	}
	return t.From
}

func (t *Timestamp) GetTo() *time.Time {
	if t == nil {
		return nil
	}
	return t.To
}

type SearchOptions struct {
	// Cursor for pagination. Use the next_cursor from the previous response to get the next page.
	Cursor *Cursor `json:"cursor,omitempty"`
	// Filter by specific event ID
	EventID *string `json:"event_id,omitempty"`
	// Maximum number of results to return
	Limit *int64 `default:"25" json:"limit"`
	// Filter by event outcome
	Status *Status `json:"status,omitempty"`
	// Filter events by timestamp range
	Timestamp *Timestamp `json:"timestamp,omitempty"`
}

func (s SearchOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchOptions) GetCursor() *Cursor {
	if s == nil {
		return nil
	}
	return s.Cursor
}

func (s *SearchOptions) GetEventID() *string {
	if s == nil {
		return nil
	}
	return s.EventID
}

func (s *SearchOptions) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

func (s *SearchOptions) GetStatus() *Status {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *SearchOptions) GetTimestamp() *Timestamp {
	if s == nil {
		return nil
	}
	return s.Timestamp
}
