// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SecureProxy - Routes webhook requests through a secure VPC proxy (ERP integration service). When set, takes precedence over enableStaticIP.
type SecureProxy struct {
	IntegrationID string `json:"integration_id"`
	UseCaseSlug   string `json:"use_case_slug"`
}

func (s *SecureProxy) GetIntegrationID() string {
	if s == nil {
		return ""
	}
	return s.IntegrationID
}

func (s *SecureProxy) GetUseCaseSlug() string {
	if s == nil {
		return ""
	}
	return s.UseCaseSlug
}
