// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Body struct {
}

type Status string

const (
	StatusSucceeded Status = "succeeded"
	StatusFailed    Status = "failed"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type TriggerWebhookResp struct {
	Body       *Body   `json:"body,omitempty"`
	Code       *string `json:"code,omitempty"`
	EndDate    *string `json:"end_date,omitempty"`
	EventID    *string `json:"event_id,omitempty"`
	Message    *string `json:"message,omitempty"`
	StartDate  *string `json:"start_date,omitempty"`
	Status     *Status `json:"status,omitempty"`
	StatusCode *string `json:"status_code,omitempty"`
}

func (t *TriggerWebhookResp) GetBody() *Body {
	if t == nil {
		return nil
	}
	return t.Body
}

func (t *TriggerWebhookResp) GetCode() *string {
	if t == nil {
		return nil
	}
	return t.Code
}

func (t *TriggerWebhookResp) GetEndDate() *string {
	if t == nil {
		return nil
	}
	return t.EndDate
}

func (t *TriggerWebhookResp) GetEventID() *string {
	if t == nil {
		return nil
	}
	return t.EventID
}

func (t *TriggerWebhookResp) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *TriggerWebhookResp) GetStartDate() *string {
	if t == nil {
		return nil
	}
	return t.StartDate
}

func (t *TriggerWebhookResp) GetStatus() *Status {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TriggerWebhookResp) GetStatusCode() *string {
	if t == nil {
		return nil
	}
	return t.StatusCode
}
