// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WebhookConfigStatus string

const (
	WebhookConfigStatusActive     WebhookConfigStatus = "active"
	WebhookConfigStatusInactive   WebhookConfigStatus = "inactive"
	WebhookConfigStatusIncomplete WebhookConfigStatus = "incomplete"
)

func (e WebhookConfigStatus) ToPointer() *WebhookConfigStatus {
	return &e
}
func (e *WebhookConfigStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "inactive":
		fallthrough
	case "incomplete":
		*e = WebhookConfigStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookConfigStatus: %v", v)
	}
}

type WebhookConfig struct {
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	Auth     *Auth    `json:"auth,omitempty"`
	// creation timestamp
	CreationTime   *string     `json:"creationTime,omitempty"`
	EnableStaticIP *bool       `json:"enableStaticIP,omitempty"`
	Enabled        *bool       `json:"enabled,omitempty"`
	EventName      string      `json:"eventName"`
	Filter         *Filter     `json:"filter,omitempty"`
	HTTPMethod     *HTTPMethod `json:"httpMethod,omitempty"`
	ID             *string     `json:"id,omitempty"`
	// JSONata expression to transform the payload
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
	Name              string  `json:"name"`
	// Configuration for the webhook payload
	PayloadConfiguration *PayloadConfiguration `json:"payloadConfiguration,omitempty"`
	Status               *WebhookConfigStatus  `json:"status,omitempty"`
	URL                  *string               `json:"url,omitempty"`
}

func (w *WebhookConfig) GetManifest() []string {
	if w == nil {
		return nil
	}
	return w.Manifest
}

func (w *WebhookConfig) GetAuth() *Auth {
	if w == nil {
		return nil
	}
	return w.Auth
}

func (w *WebhookConfig) GetCreationTime() *string {
	if w == nil {
		return nil
	}
	return w.CreationTime
}

func (w *WebhookConfig) GetEnableStaticIP() *bool {
	if w == nil {
		return nil
	}
	return w.EnableStaticIP
}

func (w *WebhookConfig) GetEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.Enabled
}

func (w *WebhookConfig) GetEventName() string {
	if w == nil {
		return ""
	}
	return w.EventName
}

func (w *WebhookConfig) GetFilter() *Filter {
	if w == nil {
		return nil
	}
	return w.Filter
}

func (w *WebhookConfig) GetHTTPMethod() *HTTPMethod {
	if w == nil {
		return nil
	}
	return w.HTTPMethod
}

func (w *WebhookConfig) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookConfig) GetJsonataExpression() *string {
	if w == nil {
		return nil
	}
	return w.JsonataExpression
}

func (w *WebhookConfig) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WebhookConfig) GetPayloadConfiguration() *PayloadConfiguration {
	if w == nil {
		return nil
	}
	return w.PayloadConfiguration
}

func (w *WebhookConfig) GetStatus() *WebhookConfigStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WebhookConfig) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}

type WebhookConfigInput struct {
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	Auth     *Auth    `json:"auth,omitempty"`
	// creation timestamp
	CreationTime   *string     `json:"creationTime,omitempty"`
	EnableStaticIP *bool       `json:"enableStaticIP,omitempty"`
	Enabled        *bool       `json:"enabled,omitempty"`
	EventName      string      `json:"eventName"`
	Filter         *Filter     `json:"filter,omitempty"`
	HTTPMethod     *HTTPMethod `json:"httpMethod,omitempty"`
	// JSONata expression to transform the payload
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
	Name              string  `json:"name"`
	// Configuration for the webhook payload
	PayloadConfiguration *PayloadConfiguration `json:"payloadConfiguration,omitempty"`
	Status               *WebhookConfigStatus  `json:"status,omitempty"`
	URL                  *string               `json:"url,omitempty"`
}

func (w *WebhookConfigInput) GetManifest() []string {
	if w == nil {
		return nil
	}
	return w.Manifest
}

func (w *WebhookConfigInput) GetAuth() *Auth {
	if w == nil {
		return nil
	}
	return w.Auth
}

func (w *WebhookConfigInput) GetCreationTime() *string {
	if w == nil {
		return nil
	}
	return w.CreationTime
}

func (w *WebhookConfigInput) GetEnableStaticIP() *bool {
	if w == nil {
		return nil
	}
	return w.EnableStaticIP
}

func (w *WebhookConfigInput) GetEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.Enabled
}

func (w *WebhookConfigInput) GetEventName() string {
	if w == nil {
		return ""
	}
	return w.EventName
}

func (w *WebhookConfigInput) GetFilter() *Filter {
	if w == nil {
		return nil
	}
	return w.Filter
}

func (w *WebhookConfigInput) GetHTTPMethod() *HTTPMethod {
	if w == nil {
		return nil
	}
	return w.HTTPMethod
}

func (w *WebhookConfigInput) GetJsonataExpression() *string {
	if w == nil {
		return nil
	}
	return w.JsonataExpression
}

func (w *WebhookConfigInput) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WebhookConfigInput) GetPayloadConfiguration() *PayloadConfiguration {
	if w == nil {
		return nil
	}
	return w.PayloadConfiguration
}

func (w *WebhookConfigInput) GetStatus() *WebhookConfigStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WebhookConfigInput) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}
