// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WebhookConfigStatus string

const (
	WebhookConfigStatusActive     WebhookConfigStatus = "active"
	WebhookConfigStatusInactive   WebhookConfigStatus = "inactive"
	WebhookConfigStatusIncomplete WebhookConfigStatus = "incomplete"
)

func (e WebhookConfigStatus) ToPointer() *WebhookConfigStatus {
	return &e
}
func (e *WebhookConfigStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "inactive":
		fallthrough
	case "incomplete":
		*e = WebhookConfigStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookConfigStatus: %v", v)
	}
}

type WebhookConfig struct {
	// Manifest ID used to create/update the webhook resource
	Manifest []string `json:"_manifest,omitempty"`
	Auth     *Auth    `json:"auth,omitempty"`
	// creation timestamp
	CreationTime *string `json:"creationTime,omitempty"`
	// Controls how file data is delivered to the endpoint. Only relevant when the webhook is triggered by a file event. Absent for non-file-event webhooks.
	DeliveryMode   *DeliveryMode `json:"deliveryMode,omitempty"`
	EnableStaticIP *bool         `json:"enableStaticIP,omitempty"`
	Enabled        *bool         `json:"enabled,omitempty"`
	EventName      string        `json:"eventName"`
	Filter         *Filter       `json:"filter,omitempty"`
	// A group of conditions with a logical operator. Multiple conditions are AND-ed by default.
	FilterConditions *WebhookConditionGroup `json:"filterConditions,omitempty"`
	HTTPMethod       *HTTPMethod            `json:"httpMethod,omitempty"`
	ID               *string                `json:"id,omitempty"`
	// JSONata expression to transform the payload
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
	// Configuration for binary_multipart delivery mode. Specifies the field names used in the multipart form data request.
	MultipartConfig *MultipartConfig `json:"multipartConfig,omitempty"`
	Name            string           `json:"name"`
	// Configuration for the webhook payload
	PayloadConfiguration *PayloadConfiguration `json:"payloadConfiguration,omitempty"`
	// When true, indicates this webhook configuration is protected and should not be modified without explicit intent.
	Protected *bool `json:"protected,omitempty"`
	// Routes webhook requests through a secure VPC proxy (ERP integration service). When set, takes precedence over enableStaticIP.
	SecureProxy *SecureProxy `json:"secureProxy,omitempty"`
	// Per-webhook signing secret following the Standard Webhooks specification.
	// Only returned once during webhook creation. Use this secret to verify
	// webhook signatures using the `webhook-id`, `webhook-timestamp`, and
	// `webhook-signature` headers.
	//
	SigningSecret *string              `json:"signingSecret,omitempty"`
	Status        *WebhookConfigStatus `json:"status,omitempty"`
	URL           *string              `json:"url,omitempty"`
}

func (w *WebhookConfig) GetManifest() []string {
	if w == nil {
		return nil
	}
	return w.Manifest
}

func (w *WebhookConfig) GetAuth() *Auth {
	if w == nil {
		return nil
	}
	return w.Auth
}

func (w *WebhookConfig) GetCreationTime() *string {
	if w == nil {
		return nil
	}
	return w.CreationTime
}

func (w *WebhookConfig) GetDeliveryMode() *DeliveryMode {
	if w == nil {
		return nil
	}
	return w.DeliveryMode
}

func (w *WebhookConfig) GetEnableStaticIP() *bool {
	if w == nil {
		return nil
	}
	return w.EnableStaticIP
}

func (w *WebhookConfig) GetEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.Enabled
}

func (w *WebhookConfig) GetEventName() string {
	if w == nil {
		return ""
	}
	return w.EventName
}

func (w *WebhookConfig) GetFilter() *Filter {
	if w == nil {
		return nil
	}
	return w.Filter
}

func (w *WebhookConfig) GetFilterConditions() *WebhookConditionGroup {
	if w == nil {
		return nil
	}
	return w.FilterConditions
}

func (w *WebhookConfig) GetHTTPMethod() *HTTPMethod {
	if w == nil {
		return nil
	}
	return w.HTTPMethod
}

func (w *WebhookConfig) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WebhookConfig) GetJsonataExpression() *string {
	if w == nil {
		return nil
	}
	return w.JsonataExpression
}

func (w *WebhookConfig) GetMultipartConfig() *MultipartConfig {
	if w == nil {
		return nil
	}
	return w.MultipartConfig
}

func (w *WebhookConfig) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WebhookConfig) GetPayloadConfiguration() *PayloadConfiguration {
	if w == nil {
		return nil
	}
	return w.PayloadConfiguration
}

func (w *WebhookConfig) GetProtected() *bool {
	if w == nil {
		return nil
	}
	return w.Protected
}

func (w *WebhookConfig) GetSecureProxy() *SecureProxy {
	if w == nil {
		return nil
	}
	return w.SecureProxy
}

func (w *WebhookConfig) GetSigningSecret() *string {
	if w == nil {
		return nil
	}
	return w.SigningSecret
}

func (w *WebhookConfig) GetStatus() *WebhookConfigStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WebhookConfig) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}

type WebhookConfigInput struct {
	// Manifest ID used to create/update the webhook resource
	Manifest []string `json:"_manifest,omitempty"`
	Auth     *Auth    `json:"auth,omitempty"`
	// creation timestamp
	CreationTime *string `json:"creationTime,omitempty"`
	// Controls how file data is delivered to the endpoint. Only relevant when the webhook is triggered by a file event. Absent for non-file-event webhooks.
	DeliveryMode   *DeliveryMode `json:"deliveryMode,omitempty"`
	EnableStaticIP *bool         `json:"enableStaticIP,omitempty"`
	Enabled        *bool         `json:"enabled,omitempty"`
	EventName      string        `json:"eventName"`
	Filter         *Filter       `json:"filter,omitempty"`
	// A group of conditions with a logical operator. Multiple conditions are AND-ed by default.
	FilterConditions *WebhookConditionGroup `json:"filterConditions,omitempty"`
	HTTPMethod       *HTTPMethod            `json:"httpMethod,omitempty"`
	// JSONata expression to transform the payload
	JsonataExpression *string `json:"jsonataExpression,omitempty"`
	// Configuration for binary_multipart delivery mode. Specifies the field names used in the multipart form data request.
	MultipartConfig *MultipartConfig `json:"multipartConfig,omitempty"`
	Name            string           `json:"name"`
	// Configuration for the webhook payload
	PayloadConfiguration *PayloadConfiguration `json:"payloadConfiguration,omitempty"`
	// When true, indicates this webhook configuration is protected and should not be modified without explicit intent.
	Protected *bool `json:"protected,omitempty"`
	// Routes webhook requests through a secure VPC proxy (ERP integration service). When set, takes precedence over enableStaticIP.
	SecureProxy *SecureProxy         `json:"secureProxy,omitempty"`
	Status      *WebhookConfigStatus `json:"status,omitempty"`
	URL         *string              `json:"url,omitempty"`
}

func (w *WebhookConfigInput) GetManifest() []string {
	if w == nil {
		return nil
	}
	return w.Manifest
}

func (w *WebhookConfigInput) GetAuth() *Auth {
	if w == nil {
		return nil
	}
	return w.Auth
}

func (w *WebhookConfigInput) GetCreationTime() *string {
	if w == nil {
		return nil
	}
	return w.CreationTime
}

func (w *WebhookConfigInput) GetDeliveryMode() *DeliveryMode {
	if w == nil {
		return nil
	}
	return w.DeliveryMode
}

func (w *WebhookConfigInput) GetEnableStaticIP() *bool {
	if w == nil {
		return nil
	}
	return w.EnableStaticIP
}

func (w *WebhookConfigInput) GetEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.Enabled
}

func (w *WebhookConfigInput) GetEventName() string {
	if w == nil {
		return ""
	}
	return w.EventName
}

func (w *WebhookConfigInput) GetFilter() *Filter {
	if w == nil {
		return nil
	}
	return w.Filter
}

func (w *WebhookConfigInput) GetFilterConditions() *WebhookConditionGroup {
	if w == nil {
		return nil
	}
	return w.FilterConditions
}

func (w *WebhookConfigInput) GetHTTPMethod() *HTTPMethod {
	if w == nil {
		return nil
	}
	return w.HTTPMethod
}

func (w *WebhookConfigInput) GetJsonataExpression() *string {
	if w == nil {
		return nil
	}
	return w.JsonataExpression
}

func (w *WebhookConfigInput) GetMultipartConfig() *MultipartConfig {
	if w == nil {
		return nil
	}
	return w.MultipartConfig
}

func (w *WebhookConfigInput) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WebhookConfigInput) GetPayloadConfiguration() *PayloadConfiguration {
	if w == nil {
		return nil
	}
	return w.PayloadConfiguration
}

func (w *WebhookConfigInput) GetProtected() *bool {
	if w == nil {
		return nil
	}
	return w.Protected
}

func (w *WebhookConfigInput) GetSecureProxy() *SecureProxy {
	if w == nil {
		return nil
	}
	return w.SecureProxy
}

func (w *WebhookConfigInput) GetStatus() *WebhookConfigStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WebhookConfigInput) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}
