// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
)

// FieldType - Type hint for the field (affects comparison logic)
type FieldType string

const (
	FieldTypeString   FieldType = "string"
	FieldTypeNumber   FieldType = "number"
	FieldTypeBoolean  FieldType = "boolean"
	FieldTypeDate     FieldType = "date"
	FieldTypeDatetime FieldType = "datetime"
)

func (e FieldType) ToPointer() *FieldType {
	return &e
}
func (e *FieldType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		fallthrough
	case "number":
		fallthrough
	case "boolean":
		fallthrough
	case "date":
		fallthrough
	case "datetime":
		*e = FieldType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FieldType: %v", v)
	}
}

type Operation string

const (
	OperationEquals              Operation = "equals"
	OperationNotEquals           Operation = "not_equals"
	OperationAnyOf               Operation = "any_of"
	OperationNoneOf              Operation = "none_of"
	OperationContains            Operation = "contains"
	OperationNotContains         Operation = "not_contains"
	OperationStartsWith          Operation = "starts_with"
	OperationEndsWith            Operation = "ends_with"
	OperationGreaterThan         Operation = "greater_than"
	OperationLessThan            Operation = "less_than"
	OperationGreaterThanOrEquals Operation = "greater_than_or_equals"
	OperationLessThanOrEquals    Operation = "less_than_or_equals"
	OperationIsEmpty             Operation = "is_empty"
	OperationIsNotEmpty          Operation = "is_not_empty"
)

func (e Operation) ToPointer() *Operation {
	return &e
}
func (e *Operation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "equals":
		fallthrough
	case "not_equals":
		fallthrough
	case "any_of":
		fallthrough
	case "none_of":
		fallthrough
	case "contains":
		fallthrough
	case "not_contains":
		fallthrough
	case "starts_with":
		fallthrough
	case "ends_with":
		fallthrough
	case "greater_than":
		fallthrough
	case "less_than":
		fallthrough
	case "greater_than_or_equals":
		fallthrough
	case "less_than_or_equals":
		fallthrough
	case "is_empty":
		fallthrough
	case "is_not_empty":
		*e = Operation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Operation: %v", v)
	}
}

// WebhookCondition - A condition that must be met for the webhook to fire.
type WebhookCondition struct {
	// Dot-notation path to the field in the event payload (e.g. "entity.status", "entity.line_items")
	Field string `json:"field"`
	// Type hint for the field (affects comparison logic)
	FieldType *FieldType `default:"string" json:"field_type"`
	// Whether the target field is an array (repeatable)
	IsArrayField *bool     `default:"false" json:"is_array_field"`
	Operation    Operation `json:"operation"`
	// Values to compare against (not required for is_empty/is_not_empty)
	Values []string `json:"values,omitempty"`
}

func (w WebhookCondition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookCondition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookCondition) GetField() string {
	if w == nil {
		return ""
	}
	return w.Field
}

func (w *WebhookCondition) GetFieldType() *FieldType {
	if w == nil {
		return nil
	}
	return w.FieldType
}

func (w *WebhookCondition) GetIsArrayField() *bool {
	if w == nil {
		return nil
	}
	return w.IsArrayField
}

func (w *WebhookCondition) GetOperation() Operation {
	if w == nil {
		return Operation("")
	}
	return w.Operation
}

func (w *WebhookCondition) GetValues() []string {
	if w == nil {
		return nil
	}
	return w.Values
}
