// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WebhookEventHTTPMethod string

const (
	WebhookEventHTTPMethodGet  WebhookEventHTTPMethod = "GET"
	WebhookEventHTTPMethodPost WebhookEventHTTPMethod = "POST"
	WebhookEventHTTPMethodPut  WebhookEventHTTPMethod = "PUT"
)

func (e WebhookEventHTTPMethod) ToPointer() *WebhookEventHTTPMethod {
	return &e
}
func (e *WebhookEventHTTPMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		fallthrough
	case "PUT":
		*e = WebhookEventHTTPMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookEventHTTPMethod: %v", v)
	}
}

type WebhookEventBody struct {
}

type HTTPResponse struct {
	Body       *WebhookEventBody `json:"body,omitempty"`
	Code       *string           `json:"code,omitempty"`
	Message    *string           `json:"message,omitempty"`
	StatusCode *int64            `json:"status_code,omitempty"`
}

func (h *HTTPResponse) GetBody() *WebhookEventBody {
	if h == nil {
		return nil
	}
	return h.Body
}

func (h *HTTPResponse) GetCode() *string {
	if h == nil {
		return nil
	}
	return h.Code
}

func (h *HTTPResponse) GetMessage() *string {
	if h == nil {
		return nil
	}
	return h.Message
}

func (h *HTTPResponse) GetStatusCode() *int64 {
	if h == nil {
		return nil
	}
	return h.StatusCode
}

type WebhookEventStatus string

const (
	WebhookEventStatusSucceeded  WebhookEventStatus = "succeeded"
	WebhookEventStatusFailed     WebhookEventStatus = "failed"
	WebhookEventStatusInProgress WebhookEventStatus = "in_progress"
	WebhookEventStatusSkipped    WebhookEventStatus = "skipped"
)

func (e WebhookEventStatus) ToPointer() *WebhookEventStatus {
	return &e
}
func (e *WebhookEventStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "in_progress":
		fallthrough
	case "skipped":
		*e = WebhookEventStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookEventStatus: %v", v)
	}
}

type WebhookEvent struct {
	CreatedAt    *string                 `json:"created_at,omitempty"`
	EventID      string                  `json:"event_id"`
	EventName    *string                 `json:"event_name,omitempty"`
	HTTPMethod   *WebhookEventHTTPMethod `json:"http_method,omitempty"`
	HTTPResponse *HTTPResponse           `json:"http_response,omitempty"`
	// Contains the metadata about the configured event
	Metadata *Metadata `json:"metadata,omitempty"`
	OrgID    string    `json:"org_id"`
	// stringified payload of the webhook request
	Payload         *string             `json:"payload,omitempty"`
	Status          *WebhookEventStatus `json:"status,omitempty"`
	URL             *string             `json:"url,omitempty"`
	WebhookConfigID string              `json:"webhook_config_id"`
}

func (w *WebhookEvent) GetCreatedAt() *string {
	if w == nil {
		return nil
	}
	return w.CreatedAt
}

func (w *WebhookEvent) GetEventID() string {
	if w == nil {
		return ""
	}
	return w.EventID
}

func (w *WebhookEvent) GetEventName() *string {
	if w == nil {
		return nil
	}
	return w.EventName
}

func (w *WebhookEvent) GetHTTPMethod() *WebhookEventHTTPMethod {
	if w == nil {
		return nil
	}
	return w.HTTPMethod
}

func (w *WebhookEvent) GetHTTPResponse() *HTTPResponse {
	if w == nil {
		return nil
	}
	return w.HTTPResponse
}

func (w *WebhookEvent) GetMetadata() *Metadata {
	if w == nil {
		return nil
	}
	return w.Metadata
}

func (w *WebhookEvent) GetOrgID() string {
	if w == nil {
		return ""
	}
	return w.OrgID
}

func (w *WebhookEvent) GetPayload() *string {
	if w == nil {
		return nil
	}
	return w.Payload
}

func (w *WebhookEvent) GetStatus() *WebhookEventStatus {
	if w == nil {
		return nil
	}
	return w.Status
}

func (w *WebhookEvent) GetURL() *string {
	if w == nil {
		return nil
	}
	return w.URL
}

func (w *WebhookEvent) GetWebhookConfigID() string {
	if w == nil {
		return ""
	}
	return w.WebhookConfigID
}
