// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/internal/utils"
)

type LogicalOperator string

const (
	LogicalOperatorAnd LogicalOperator = "AND"
	LogicalOperatorOr  LogicalOperator = "OR"
)

func (e LogicalOperator) ToPointer() *LogicalOperator {
	return &e
}
func (e *LogicalOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = LogicalOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LogicalOperator: %v", v)
	}
}

// WebhookConditionGroup - A group of conditions with a logical operator. Multiple conditions are AND-ed by default.
type WebhookConditionGroup struct {
	Conditions      []WebhookCondition `json:"conditions,omitempty"`
	LogicalOperator *LogicalOperator   `default:"AND" json:"logical_operator"`
}

func (w WebhookConditionGroup) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookConditionGroup) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookConditionGroup) GetConditions() []WebhookCondition {
	if w == nil {
		return nil
	}
	return w.Conditions
}

func (w *WebhookConditionGroup) GetLogicalOperator() *LogicalOperator {
	if w == nil {
		return nil
	}
	return w.LogicalOperator
}
