// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *WebhookDataSourceModel) RefreshFromSharedWebhookConfig(ctx context.Context, resp *shared.WebhookConfig) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		if resp.Auth == nil {
			r.Auth = nil
		} else {
			r.Auth = &tfTypes.Auth{}
			if resp.Auth.APIKeyConfig == nil {
				r.Auth.APIKeyConfig = nil
			} else {
				r.Auth.APIKeyConfig = &tfTypes.APIKeyConfig{}
				r.Auth.APIKeyConfig.KeyName = types.StringValue(resp.Auth.APIKeyConfig.KeyName)
				r.Auth.APIKeyConfig.KeyValue = types.StringPointerValue(resp.Auth.APIKeyConfig.KeyValue)
			}
			r.Auth.AuthType = types.StringValue(string(resp.Auth.AuthType))
			if resp.Auth.BasicAuthConfig == nil {
				r.Auth.BasicAuthConfig = nil
			} else {
				r.Auth.BasicAuthConfig = &tfTypes.BasicAuthConfig{}
				r.Auth.BasicAuthConfig.Password = types.StringPointerValue(resp.Auth.BasicAuthConfig.Password)
				r.Auth.BasicAuthConfig.Username = types.StringValue(resp.Auth.BasicAuthConfig.Username)
			}
			if resp.Auth.OauthConfig == nil {
				r.Auth.OauthConfig = nil
			} else {
				r.Auth.OauthConfig = &tfTypes.OAuthConfig{}
				r.Auth.OauthConfig.ClientID = types.StringValue(resp.Auth.OauthConfig.ClientID)
				r.Auth.OauthConfig.ClientSecret = types.StringPointerValue(resp.Auth.OauthConfig.ClientSecret)
				r.Auth.OauthConfig.CustomParameterList = []tfTypes.CustomOAuthParameter{}

				for _, customParameterListItem := range resp.Auth.OauthConfig.CustomParameterList {
					var customParameterList tfTypes.CustomOAuthParameter

					customParameterList.Key = types.StringValue(customParameterListItem.Key)
					customParameterList.Type = types.StringValue(string(customParameterListItem.Type))
					customParameterList.Value = types.StringValue(customParameterListItem.Value)

					r.Auth.OauthConfig.CustomParameterList = append(r.Auth.OauthConfig.CustomParameterList, customParameterList)
				}
				r.Auth.OauthConfig.Endpoint = types.StringValue(resp.Auth.OauthConfig.Endpoint)
				r.Auth.OauthConfig.HTTPMethod = types.StringValue(string(resp.Auth.OauthConfig.HTTPMethod))
			}
		}
		r.CreationTime = types.StringPointerValue(resp.CreationTime)
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.EnableStaticIP = types.BoolPointerValue(resp.EnableStaticIP)
		r.EventName = types.StringValue(resp.EventName)
		if resp.Filter == nil {
			r.Filter = nil
		} else {
			r.Filter = &tfTypes.Filter{}
			r.Filter.KeyToFilter = types.StringValue(resp.Filter.KeyToFilter)
			r.Filter.SupportedValues = make([]types.String, 0, len(resp.Filter.SupportedValues))
			for _, v := range resp.Filter.SupportedValues {
				r.Filter.SupportedValues = append(r.Filter.SupportedValues, types.StringValue(v))
			}
		}
		if resp.FilterConditions == nil {
			r.FilterConditions = nil
		} else {
			r.FilterConditions = &tfTypes.WebhookConditionGroup{}
			r.FilterConditions.Conditions = []tfTypes.WebhookCondition{}

			for _, conditionsItem := range resp.FilterConditions.Conditions {
				var conditions tfTypes.WebhookCondition

				conditions.Field = types.StringValue(conditionsItem.Field)
				if conditionsItem.FieldType != nil {
					conditions.FieldType = types.StringValue(string(*conditionsItem.FieldType))
				} else {
					conditions.FieldType = types.StringNull()
				}
				conditions.IsArrayField = types.BoolPointerValue(conditionsItem.IsArrayField)
				conditions.Operation = types.StringValue(string(conditionsItem.Operation))
				conditions.Values = make([]types.String, 0, len(conditionsItem.Values))
				for _, v := range conditionsItem.Values {
					conditions.Values = append(conditions.Values, types.StringValue(v))
				}

				r.FilterConditions.Conditions = append(r.FilterConditions.Conditions, conditions)
			}
			if resp.FilterConditions.LogicalOperator != nil {
				r.FilterConditions.LogicalOperator = types.StringValue(string(*resp.FilterConditions.LogicalOperator))
			} else {
				r.FilterConditions.LogicalOperator = types.StringNull()
			}
		}
		if resp.HTTPMethod != nil {
			r.HTTPMethod = types.StringValue(string(*resp.HTTPMethod))
		} else {
			r.HTTPMethod = types.StringNull()
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.JsonataExpression = types.StringPointerValue(resp.JsonataExpression)
		r.Name = types.StringValue(resp.Name)
		if resp.PayloadConfiguration == nil {
			r.PayloadConfiguration = nil
		} else {
			r.PayloadConfiguration = &tfTypes.PayloadConfiguration{}
			if len(resp.PayloadConfiguration.CustomHeaders) > 0 {
				r.PayloadConfiguration.CustomHeaders = make(map[string]types.String, len(resp.PayloadConfiguration.CustomHeaders))
				for key, value := range resp.PayloadConfiguration.CustomHeaders {
					r.PayloadConfiguration.CustomHeaders[key] = types.StringValue(value)
				}
			}
			r.PayloadConfiguration.HydrateEntity = types.BoolPointerValue(resp.PayloadConfiguration.HydrateEntity)
			r.PayloadConfiguration.IncludeActivity = types.BoolPointerValue(resp.PayloadConfiguration.IncludeActivity)
			r.PayloadConfiguration.IncludeChangedAttributes = types.BoolPointerValue(resp.PayloadConfiguration.IncludeChangedAttributes)
			r.PayloadConfiguration.IncludeRelations = types.BoolPointerValue(resp.PayloadConfiguration.IncludeRelations)
		}
		r.SigningSecret = types.StringPointerValue(resp.SigningSecret)
		if resp.Status != nil {
			r.Status = types.StringValue(string(*resp.Status))
		} else {
			r.Status = types.StringNull()
		}
		r.URL = types.StringPointerValue(resp.URL)
	}

	return diags
}

func (r *WebhookDataSourceModel) ToOperationsGetConfigRequest(ctx context.Context) (*operations.GetConfigRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var configID string
	configID = r.ID.ValueString()

	out := operations.GetConfigRequest{
		ConfigID: configID,
	}

	return &out, diags
}
