// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *WebhookResourceModel) RefreshFromSharedWebhookConfig(ctx context.Context, resp *shared.WebhookConfig) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		if resp.Auth == nil {
			r.Auth = nil
		} else {
			r.Auth = &tfTypes.Auth{}
			if resp.Auth.APIKeyConfig == nil {
				r.Auth.APIKeyConfig = nil
			} else {
				r.Auth.APIKeyConfig = &tfTypes.APIKeyConfig{}
				r.Auth.APIKeyConfig.KeyName = types.StringValue(resp.Auth.APIKeyConfig.KeyName)
				r.Auth.APIKeyConfig.KeyValue = types.StringPointerValue(resp.Auth.APIKeyConfig.KeyValue)
				r.Auth.APIKeyConfig.KeyValueIsEnvVar = types.BoolPointerValue(resp.Auth.APIKeyConfig.KeyValueIsEnvVar)
			}
			r.Auth.AuthType = types.StringValue(string(resp.Auth.AuthType))
			if resp.Auth.BasicAuthConfig == nil {
				r.Auth.BasicAuthConfig = nil
			} else {
				r.Auth.BasicAuthConfig = &tfTypes.BasicAuthConfig{}
				r.Auth.BasicAuthConfig.Password = types.StringPointerValue(resp.Auth.BasicAuthConfig.Password)
				r.Auth.BasicAuthConfig.PasswordIsEnvVar = types.BoolPointerValue(resp.Auth.BasicAuthConfig.PasswordIsEnvVar)
				r.Auth.BasicAuthConfig.Username = types.StringValue(resp.Auth.BasicAuthConfig.Username)
			}
			if resp.Auth.OauthConfig == nil {
				r.Auth.OauthConfig = nil
			} else {
				r.Auth.OauthConfig = &tfTypes.OAuthConfig{}
				r.Auth.OauthConfig.ClientID = types.StringValue(resp.Auth.OauthConfig.ClientID)
				r.Auth.OauthConfig.ClientSecret = types.StringPointerValue(resp.Auth.OauthConfig.ClientSecret)
				r.Auth.OauthConfig.ClientSecretIsEnvVar = types.BoolPointerValue(resp.Auth.OauthConfig.ClientSecretIsEnvVar)
				r.Auth.OauthConfig.CustomParameterList = []tfTypes.CustomOAuthParameter{}

				for _, customParameterListItem := range resp.Auth.OauthConfig.CustomParameterList {
					var customParameterList tfTypes.CustomOAuthParameter

					customParameterList.Key = types.StringValue(customParameterListItem.Key)
					customParameterList.Type = types.StringValue(string(customParameterListItem.Type))
					customParameterList.Value = types.StringValue(customParameterListItem.Value)

					r.Auth.OauthConfig.CustomParameterList = append(r.Auth.OauthConfig.CustomParameterList, customParameterList)
				}
				r.Auth.OauthConfig.Endpoint = types.StringValue(resp.Auth.OauthConfig.Endpoint)
				r.Auth.OauthConfig.HTTPMethod = types.StringValue(string(resp.Auth.OauthConfig.HTTPMethod))
			}
		}
		r.CreationTime = types.StringPointerValue(resp.CreationTime)
		if resp.DeliveryMode != nil {
			r.DeliveryMode = types.StringValue(string(*resp.DeliveryMode))
		} else {
			r.DeliveryMode = types.StringNull()
		}
		r.Enabled = types.BoolPointerValue(resp.Enabled)
		r.EnableStaticIP = types.BoolPointerValue(resp.EnableStaticIP)
		r.EventName = types.StringValue(resp.EventName)
		if resp.Filter == nil {
			r.Filter = nil
		} else {
			r.Filter = &tfTypes.Filter{}
			r.Filter.KeyToFilter = types.StringValue(resp.Filter.KeyToFilter)
			r.Filter.SupportedValues = make([]types.String, 0, len(resp.Filter.SupportedValues))
			for _, v := range resp.Filter.SupportedValues {
				r.Filter.SupportedValues = append(r.Filter.SupportedValues, types.StringValue(v))
			}
		}
		if resp.FilterConditions == nil {
			r.FilterConditions = nil
		} else {
			r.FilterConditions = &tfTypes.WebhookConditionGroup{}
			r.FilterConditions.Conditions = []tfTypes.WebhookCondition{}

			for _, conditionsItem := range resp.FilterConditions.Conditions {
				var conditions tfTypes.WebhookCondition

				conditions.Field = types.StringValue(conditionsItem.Field)
				if conditionsItem.FieldType != nil {
					conditions.FieldType = types.StringValue(string(*conditionsItem.FieldType))
				} else {
					conditions.FieldType = types.StringNull()
				}
				conditions.IsArrayField = types.BoolPointerValue(conditionsItem.IsArrayField)
				conditions.Operation = types.StringValue(string(conditionsItem.Operation))
				conditions.RepeatableItemOp = types.BoolPointerValue(conditionsItem.RepeatableItemOp)
				conditions.Values = make([]types.String, 0, len(conditionsItem.Values))
				for _, v := range conditionsItem.Values {
					conditions.Values = append(conditions.Values, types.StringValue(v))
				}

				r.FilterConditions.Conditions = append(r.FilterConditions.Conditions, conditions)
			}
			if resp.FilterConditions.LogicalOperator != nil {
				r.FilterConditions.LogicalOperator = types.StringValue(string(*resp.FilterConditions.LogicalOperator))
			} else {
				r.FilterConditions.LogicalOperator = types.StringNull()
			}
		}
		if resp.HTTPMethod != nil {
			r.HTTPMethod = types.StringValue(string(*resp.HTTPMethod))
		} else {
			r.HTTPMethod = types.StringNull()
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.JsonataExpression = types.StringPointerValue(resp.JsonataExpression)
		if resp.MultipartConfig == nil {
			r.MultipartConfig = nil
		} else {
			r.MultipartConfig = &tfTypes.MultipartConfig{}
			r.MultipartConfig.FileFieldName = types.StringPointerValue(resp.MultipartConfig.FileFieldName)
			r.MultipartConfig.MetadataFieldName = types.StringPointerValue(resp.MultipartConfig.MetadataFieldName)
		}
		r.Name = types.StringValue(resp.Name)
		if resp.PayloadConfiguration == nil {
			r.PayloadConfiguration = nil
		} else {
			r.PayloadConfiguration = &tfTypes.PayloadConfiguration{}
			r.PayloadConfiguration.ApplyChangesets = types.BoolPointerValue(resp.PayloadConfiguration.ApplyChangesets)
			if len(resp.PayloadConfiguration.CustomHeaders) > 0 {
				r.PayloadConfiguration.CustomHeaders = make(map[string]types.String, len(resp.PayloadConfiguration.CustomHeaders))
				for key, value := range resp.PayloadConfiguration.CustomHeaders {
					r.PayloadConfiguration.CustomHeaders[key] = types.StringValue(value)
				}
			}
			r.PayloadConfiguration.HydrateEntity = types.BoolPointerValue(resp.PayloadConfiguration.HydrateEntity)
			r.PayloadConfiguration.IncludeActivity = types.BoolPointerValue(resp.PayloadConfiguration.IncludeActivity)
			r.PayloadConfiguration.IncludeChangedAttributes = types.BoolPointerValue(resp.PayloadConfiguration.IncludeChangedAttributes)
			r.PayloadConfiguration.IncludeRelations = types.BoolPointerValue(resp.PayloadConfiguration.IncludeRelations)
		}
		r.Protected = types.BoolPointerValue(resp.Protected)
		if resp.SecureProxy == nil {
			r.SecureProxy = nil
		} else {
			r.SecureProxy = &tfTypes.SecureProxy{}
			r.SecureProxy.IntegrationID = types.StringValue(resp.SecureProxy.IntegrationID)
			r.SecureProxy.UseCaseSlug = types.StringValue(resp.SecureProxy.UseCaseSlug)
		}
		r.SigningSecret = types.StringPointerValue(resp.SigningSecret)
		if resp.Status != nil {
			r.Status = types.StringValue(string(*resp.Status))
		} else {
			r.Status = types.StringNull()
		}
		r.URL = types.StringPointerValue(resp.URL)
	}

	return diags
}

func (r *WebhookResourceModel) ToOperationsDeleteConfigRequest(ctx context.Context) (*operations.DeleteConfigRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var configID string
	configID = r.ID.ValueString()

	out := operations.DeleteConfigRequest{
		ConfigID: configID,
	}

	return &out, diags
}

func (r *WebhookResourceModel) ToOperationsGetConfigRequest(ctx context.Context) (*operations.GetConfigRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var configID string
	configID = r.ID.ValueString()

	out := operations.GetConfigRequest{
		ConfigID: configID,
	}

	return &out, diags
}

func (r *WebhookResourceModel) ToOperationsUpdateConfigRequest(ctx context.Context) (*operations.UpdateConfigRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	webhookConfig, webhookConfigDiags := r.ToSharedWebhookConfigInput(ctx)
	diags.Append(webhookConfigDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var configID string
	configID = r.ID.ValueString()

	out := operations.UpdateConfigRequest{
		WebhookConfig: *webhookConfig,
		ConfigID:      configID,
	}

	return &out, diags
}

func (r *WebhookResourceModel) ToSharedWebhookConfigInput(ctx context.Context) (*shared.WebhookConfigInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	manifest := make([]string, 0, len(r.Manifest))
	for manifestIndex := range r.Manifest {
		manifest = append(manifest, r.Manifest[manifestIndex].ValueString())
	}
	var auth *shared.Auth
	if r.Auth != nil {
		var apiKeyConfig *shared.APIKeyConfig
		if r.Auth.APIKeyConfig != nil {
			var keyName string
			keyName = r.Auth.APIKeyConfig.KeyName.ValueString()

			keyValue := new(string)
			if !r.Auth.APIKeyConfig.KeyValue.IsUnknown() && !r.Auth.APIKeyConfig.KeyValue.IsNull() {
				*keyValue = r.Auth.APIKeyConfig.KeyValue.ValueString()
			} else {
				keyValue = nil
			}
			keyValueIsEnvVar := new(bool)
			if !r.Auth.APIKeyConfig.KeyValueIsEnvVar.IsUnknown() && !r.Auth.APIKeyConfig.KeyValueIsEnvVar.IsNull() {
				*keyValueIsEnvVar = r.Auth.APIKeyConfig.KeyValueIsEnvVar.ValueBool()
			} else {
				keyValueIsEnvVar = nil
			}
			apiKeyConfig = &shared.APIKeyConfig{
				KeyName:          keyName,
				KeyValue:         keyValue,
				KeyValueIsEnvVar: keyValueIsEnvVar,
			}
		}
		authType := shared.AuthType(r.Auth.AuthType.ValueString())
		var basicAuthConfig *shared.BasicAuthConfig
		if r.Auth.BasicAuthConfig != nil {
			password := new(string)
			if !r.Auth.BasicAuthConfig.Password.IsUnknown() && !r.Auth.BasicAuthConfig.Password.IsNull() {
				*password = r.Auth.BasicAuthConfig.Password.ValueString()
			} else {
				password = nil
			}
			passwordIsEnvVar := new(bool)
			if !r.Auth.BasicAuthConfig.PasswordIsEnvVar.IsUnknown() && !r.Auth.BasicAuthConfig.PasswordIsEnvVar.IsNull() {
				*passwordIsEnvVar = r.Auth.BasicAuthConfig.PasswordIsEnvVar.ValueBool()
			} else {
				passwordIsEnvVar = nil
			}
			var username string
			username = r.Auth.BasicAuthConfig.Username.ValueString()

			basicAuthConfig = &shared.BasicAuthConfig{
				Password:         password,
				PasswordIsEnvVar: passwordIsEnvVar,
				Username:         username,
			}
		}
		var oauthConfig *shared.OAuthConfig
		if r.Auth.OauthConfig != nil {
			var clientID string
			clientID = r.Auth.OauthConfig.ClientID.ValueString()

			clientSecret := new(string)
			if !r.Auth.OauthConfig.ClientSecret.IsUnknown() && !r.Auth.OauthConfig.ClientSecret.IsNull() {
				*clientSecret = r.Auth.OauthConfig.ClientSecret.ValueString()
			} else {
				clientSecret = nil
			}
			clientSecretIsEnvVar := new(bool)
			if !r.Auth.OauthConfig.ClientSecretIsEnvVar.IsUnknown() && !r.Auth.OauthConfig.ClientSecretIsEnvVar.IsNull() {
				*clientSecretIsEnvVar = r.Auth.OauthConfig.ClientSecretIsEnvVar.ValueBool()
			} else {
				clientSecretIsEnvVar = nil
			}
			customParameterList := make([]shared.CustomOAuthParameter, 0, len(r.Auth.OauthConfig.CustomParameterList))
			for customParameterListIndex := range r.Auth.OauthConfig.CustomParameterList {
				var key string
				key = r.Auth.OauthConfig.CustomParameterList[customParameterListIndex].Key.ValueString()

				typeVar := shared.Type(r.Auth.OauthConfig.CustomParameterList[customParameterListIndex].Type.ValueString())
				var value string
				value = r.Auth.OauthConfig.CustomParameterList[customParameterListIndex].Value.ValueString()

				customParameterList = append(customParameterList, shared.CustomOAuthParameter{
					Key:   key,
					Type:  typeVar,
					Value: value,
				})
			}
			var endpoint string
			endpoint = r.Auth.OauthConfig.Endpoint.ValueString()

			httpMethod := shared.HTTPMethod(r.Auth.OauthConfig.HTTPMethod.ValueString())
			oauthConfig = &shared.OAuthConfig{
				ClientID:             clientID,
				ClientSecret:         clientSecret,
				ClientSecretIsEnvVar: clientSecretIsEnvVar,
				CustomParameterList:  customParameterList,
				Endpoint:             endpoint,
				HTTPMethod:           httpMethod,
			}
		}
		auth = &shared.Auth{
			APIKeyConfig:    apiKeyConfig,
			AuthType:        authType,
			BasicAuthConfig: basicAuthConfig,
			OauthConfig:     oauthConfig,
		}
	}
	creationTime := new(string)
	if !r.CreationTime.IsUnknown() && !r.CreationTime.IsNull() {
		*creationTime = r.CreationTime.ValueString()
	} else {
		creationTime = nil
	}
	deliveryMode := new(shared.DeliveryMode)
	if !r.DeliveryMode.IsUnknown() && !r.DeliveryMode.IsNull() {
		*deliveryMode = shared.DeliveryMode(r.DeliveryMode.ValueString())
	} else {
		deliveryMode = nil
	}
	enableStaticIP := new(bool)
	if !r.EnableStaticIP.IsUnknown() && !r.EnableStaticIP.IsNull() {
		*enableStaticIP = r.EnableStaticIP.ValueBool()
	} else {
		enableStaticIP = nil
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	var eventName string
	eventName = r.EventName.ValueString()

	var filter *shared.Filter
	if r.Filter != nil {
		var keyToFilter string
		keyToFilter = r.Filter.KeyToFilter.ValueString()

		supportedValues := make([]string, 0, len(r.Filter.SupportedValues))
		for supportedValuesIndex := range r.Filter.SupportedValues {
			supportedValues = append(supportedValues, r.Filter.SupportedValues[supportedValuesIndex].ValueString())
		}
		filter = &shared.Filter{
			KeyToFilter:     keyToFilter,
			SupportedValues: supportedValues,
		}
	}
	var filterConditions *shared.WebhookConditionGroup
	if r.FilterConditions != nil {
		conditions := make([]shared.WebhookCondition, 0, len(r.FilterConditions.Conditions))
		for conditionsIndex := range r.FilterConditions.Conditions {
			var field string
			field = r.FilterConditions.Conditions[conditionsIndex].Field.ValueString()

			fieldType := new(shared.FieldType)
			if !r.FilterConditions.Conditions[conditionsIndex].FieldType.IsUnknown() && !r.FilterConditions.Conditions[conditionsIndex].FieldType.IsNull() {
				*fieldType = shared.FieldType(r.FilterConditions.Conditions[conditionsIndex].FieldType.ValueString())
			} else {
				fieldType = nil
			}
			isArrayField := new(bool)
			if !r.FilterConditions.Conditions[conditionsIndex].IsArrayField.IsUnknown() && !r.FilterConditions.Conditions[conditionsIndex].IsArrayField.IsNull() {
				*isArrayField = r.FilterConditions.Conditions[conditionsIndex].IsArrayField.ValueBool()
			} else {
				isArrayField = nil
			}
			operation := shared.Operation(r.FilterConditions.Conditions[conditionsIndex].Operation.ValueString())
			repeatableItemOp := new(bool)
			if !r.FilterConditions.Conditions[conditionsIndex].RepeatableItemOp.IsUnknown() && !r.FilterConditions.Conditions[conditionsIndex].RepeatableItemOp.IsNull() {
				*repeatableItemOp = r.FilterConditions.Conditions[conditionsIndex].RepeatableItemOp.ValueBool()
			} else {
				repeatableItemOp = nil
			}
			values := make([]string, 0, len(r.FilterConditions.Conditions[conditionsIndex].Values))
			for valuesIndex := range r.FilterConditions.Conditions[conditionsIndex].Values {
				values = append(values, r.FilterConditions.Conditions[conditionsIndex].Values[valuesIndex].ValueString())
			}
			conditions = append(conditions, shared.WebhookCondition{
				Field:            field,
				FieldType:        fieldType,
				IsArrayField:     isArrayField,
				Operation:        operation,
				RepeatableItemOp: repeatableItemOp,
				Values:           values,
			})
		}
		logicalOperator := new(shared.LogicalOperator)
		if !r.FilterConditions.LogicalOperator.IsUnknown() && !r.FilterConditions.LogicalOperator.IsNull() {
			*logicalOperator = shared.LogicalOperator(r.FilterConditions.LogicalOperator.ValueString())
		} else {
			logicalOperator = nil
		}
		filterConditions = &shared.WebhookConditionGroup{
			Conditions:      conditions,
			LogicalOperator: logicalOperator,
		}
	}
	httpMethod1 := new(shared.HTTPMethod)
	if !r.HTTPMethod.IsUnknown() && !r.HTTPMethod.IsNull() {
		*httpMethod1 = shared.HTTPMethod(r.HTTPMethod.ValueString())
	} else {
		httpMethod1 = nil
	}
	var jsonataExpression *string
	if !r.JsonataExpression.IsUnknown() && !r.JsonataExpression.IsNull() && r.JsonataExpression.ValueString() != "" {
		val := r.JsonataExpression.ValueString()
		jsonataExpression = &val
	}
	var multipartConfig *shared.MultipartConfig
	if r.MultipartConfig != nil {
		fileFieldName := new(string)
		if !r.MultipartConfig.FileFieldName.IsUnknown() && !r.MultipartConfig.FileFieldName.IsNull() {
			*fileFieldName = r.MultipartConfig.FileFieldName.ValueString()
		} else {
			fileFieldName = nil
		}
		metadataFieldName := new(string)
		if !r.MultipartConfig.MetadataFieldName.IsUnknown() && !r.MultipartConfig.MetadataFieldName.IsNull() {
			*metadataFieldName = r.MultipartConfig.MetadataFieldName.ValueString()
		} else {
			metadataFieldName = nil
		}
		multipartConfig = &shared.MultipartConfig{
			FileFieldName:     fileFieldName,
			MetadataFieldName: metadataFieldName,
		}
	}
	var name string
	name = r.Name.ValueString()

	var payloadConfiguration *shared.PayloadConfiguration
	if r.PayloadConfiguration != nil {
		applyChangesets := new(bool)
		if !r.PayloadConfiguration.ApplyChangesets.IsUnknown() && !r.PayloadConfiguration.ApplyChangesets.IsNull() {
			*applyChangesets = r.PayloadConfiguration.ApplyChangesets.ValueBool()
		} else {
			applyChangesets = nil
		}
		customHeaders := make(map[string]string)
		for customHeadersKey := range r.PayloadConfiguration.CustomHeaders {
			var customHeadersInst string
			customHeadersInst = r.PayloadConfiguration.CustomHeaders[customHeadersKey].ValueString()

			customHeaders[customHeadersKey] = customHeadersInst
		}
		hydrateEntity := new(bool)
		if !r.PayloadConfiguration.HydrateEntity.IsUnknown() && !r.PayloadConfiguration.HydrateEntity.IsNull() {
			*hydrateEntity = r.PayloadConfiguration.HydrateEntity.ValueBool()
		} else {
			hydrateEntity = nil
		}
		includeActivity := new(bool)
		if !r.PayloadConfiguration.IncludeActivity.IsUnknown() && !r.PayloadConfiguration.IncludeActivity.IsNull() {
			*includeActivity = r.PayloadConfiguration.IncludeActivity.ValueBool()
		} else {
			includeActivity = nil
		}
		includeChangedAttributes := new(bool)
		if !r.PayloadConfiguration.IncludeChangedAttributes.IsUnknown() && !r.PayloadConfiguration.IncludeChangedAttributes.IsNull() {
			*includeChangedAttributes = r.PayloadConfiguration.IncludeChangedAttributes.ValueBool()
		} else {
			includeChangedAttributes = nil
		}
		includeRelations := new(bool)
		if !r.PayloadConfiguration.IncludeRelations.IsUnknown() && !r.PayloadConfiguration.IncludeRelations.IsNull() {
			*includeRelations = r.PayloadConfiguration.IncludeRelations.ValueBool()
		} else {
			includeRelations = nil
		}
		payloadConfiguration = &shared.PayloadConfiguration{
			ApplyChangesets:          applyChangesets,
			CustomHeaders:            customHeaders,
			HydrateEntity:            hydrateEntity,
			IncludeActivity:          includeActivity,
			IncludeChangedAttributes: includeChangedAttributes,
			IncludeRelations:         includeRelations,
		}
	}
	protected := new(bool)
	if !r.Protected.IsUnknown() && !r.Protected.IsNull() {
		*protected = r.Protected.ValueBool()
	} else {
		protected = nil
	}
	var secureProxy *shared.SecureProxy
	if r.SecureProxy != nil {
		var integrationID string
		integrationID = r.SecureProxy.IntegrationID.ValueString()

		var useCaseSlug string
		useCaseSlug = r.SecureProxy.UseCaseSlug.ValueString()

		secureProxy = &shared.SecureProxy{
			IntegrationID: integrationID,
			UseCaseSlug:   useCaseSlug,
		}
	}
	status := new(shared.WebhookConfigStatus)
	if !r.Status.IsUnknown() && !r.Status.IsNull() {
		*status = shared.WebhookConfigStatus(r.Status.ValueString())
	} else {
		status = nil
	}
	url := new(string)
	if !r.URL.IsUnknown() && !r.URL.IsNull() {
		*url = r.URL.ValueString()
	} else {
		url = nil
	}
	out := shared.WebhookConfigInput{
		Manifest:             manifest,
		Auth:                 auth,
		CreationTime:         creationTime,
		DeliveryMode:         deliveryMode,
		EnableStaticIP:       enableStaticIP,
		Enabled:              enabled,
		EventName:            eventName,
		Filter:               filter,
		FilterConditions:     filterConditions,
		HTTPMethod:           httpMethod1,
		JsonataExpression:    jsonataExpression,
		MultipartConfig:      multipartConfig,
		Name:                 name,
		PayloadConfiguration: payloadConfiguration,
		Protected:            protected,
		SecureProxy:          secureProxy,
		Status:               status,
		URL:                  url,
	}

	return &out, diags
}
