// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-webhook/internal/sdk"
	speakeasy_listvalidators "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/validators/listvalidators"
	speakeasy_objectvalidators "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/validators/objectvalidators"
	speakeasy_stringvalidators "github.com/epilot-dev/terraform-provider-epilot-webhook/internal/validators/stringvalidators"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &WebhookResource{}
var _ resource.ResourceWithImportState = &WebhookResource{}

func NewWebhookResource() resource.Resource {
	return &WebhookResource{}
}

// WebhookResource defines the resource implementation.
type WebhookResource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// WebhookResourceModel describes the resource data model.
type WebhookResourceModel struct {
	Auth                 *tfTypes.Auth                  `tfsdk:"auth"`
	CreationTime         types.String                   `tfsdk:"creation_time"`
	Enabled              types.Bool                     `tfsdk:"enabled"`
	EnableStaticIP       types.Bool                     `tfsdk:"enable_static_ip"`
	EventName            types.String                   `tfsdk:"event_name"`
	Filter               *tfTypes.Filter                `tfsdk:"filter"`
	FilterConditions     *tfTypes.WebhookConditionGroup `tfsdk:"filter_conditions"`
	HTTPMethod           types.String                   `tfsdk:"http_method"`
	ID                   types.String                   `tfsdk:"id"`
	JsonataExpression    types.String                   `tfsdk:"jsonata_expression"`
	Manifest             []types.String                 `tfsdk:"manifest"`
	Name                 types.String                   `tfsdk:"name"`
	PayloadConfiguration *tfTypes.PayloadConfiguration  `tfsdk:"payload_configuration"`
	SigningSecret        types.String                   `tfsdk:"signing_secret"`
	Status               types.String                   `tfsdk:"status"`
	URL                  types.String                   `tfsdk:"url"`
}

func (r *WebhookResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhook"
}

func (r *WebhookResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Webhook Resource",
		Attributes: map[string]schema.Attribute{
			"auth": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"api_key_config": schema.SingleNestedAttribute{
						Computed: true,
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"key_name": schema.StringAttribute{
								Computed:    true,
								Optional:    true,
								Description: `Not Null`,
								Validators: []validator.String{
									speakeasy_stringvalidators.NotNull(),
								},
							},
							"key_value": schema.StringAttribute{
								Computed: true,
								Optional: true,
							},
						},
						Description: `To be sent only if authType is API_KEY`,
					},
					"auth_type": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Not Null; must be one of ["BASIC", "OAUTH_CLIENT_CREDENTIALS", "API_KEY", "NONE"]`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
							stringvalidator.OneOf(
								"BASIC",
								"OAUTH_CLIENT_CREDENTIALS",
								"API_KEY",
								"NONE",
							),
						},
					},
					"basic_auth_config": schema.SingleNestedAttribute{
						Computed: true,
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"password": schema.StringAttribute{
								Computed: true,
								Optional: true,
							},
							"username": schema.StringAttribute{
								Computed:    true,
								Optional:    true,
								Description: `Not Null`,
								Validators: []validator.String{
									speakeasy_stringvalidators.NotNull(),
								},
							},
						},
						Description: `To be sent only if authType is BASIC`,
					},
					"oauth_config": schema.SingleNestedAttribute{
						Computed: true,
						Optional: true,
						Attributes: map[string]schema.Attribute{
							"client_id": schema.StringAttribute{
								Computed:    true,
								Optional:    true,
								Description: `Not Null`,
								Validators: []validator.String{
									speakeasy_stringvalidators.NotNull(),
								},
							},
							"client_secret": schema.StringAttribute{
								Computed: true,
								Optional: true,
							},
							"custom_parameter_list": schema.ListNestedAttribute{
								Computed: true,
								Optional: true,
								NestedObject: schema.NestedAttributeObject{
									Validators: []validator.Object{
										speakeasy_objectvalidators.NotNull(),
									},
									Attributes: map[string]schema.Attribute{
										"key": schema.StringAttribute{
											Computed:    true,
											Optional:    true,
											Description: `Not Null`,
											Validators: []validator.String{
												speakeasy_stringvalidators.NotNull(),
											},
										},
										"type": schema.StringAttribute{
											Computed:    true,
											Optional:    true,
											Description: `Not Null; must be one of ["body", "query", "header"]`,
											Validators: []validator.String{
												speakeasy_stringvalidators.NotNull(),
												stringvalidator.OneOf(
													"body",
													"query",
													"header",
												),
											},
										},
										"value": schema.StringAttribute{
											Computed:    true,
											Optional:    true,
											Description: `Not Null`,
											Validators: []validator.String{
												speakeasy_stringvalidators.NotNull(),
											},
										},
									},
								},
							},
							"endpoint": schema.StringAttribute{
								Computed:    true,
								Optional:    true,
								Description: `Https Endpoint for authentication. Not Null`,
								Validators: []validator.String{
									speakeasy_stringvalidators.NotNull(),
								},
							},
							"http_method": schema.StringAttribute{
								Computed:    true,
								Optional:    true,
								Description: `Not Null; must be one of ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]`,
								Validators: []validator.String{
									speakeasy_stringvalidators.NotNull(),
									stringvalidator.OneOf(
										"GET",
										"POST",
										"PUT",
										"PATCH",
										"DELETE",
										"OPTIONS",
										"HEAD",
									),
								},
							},
						},
						Description: `To be sent only if authType is OAUTH_CLIENT_CREDENTIALS`,
					},
				},
			},
			"creation_time": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `creation timestamp`,
			},
			"enable_static_ip": schema.BoolAttribute{
				Computed: true,
				Optional: true,
			},
			"enabled": schema.BoolAttribute{
				Computed: true,
				Optional: true,
			},
			"event_name": schema.StringAttribute{
				Required: true,
			},
			"filter": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"key_to_filter": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Not Null`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
						},
					},
					"supported_values": schema.ListAttribute{
						Computed:    true,
						Optional:    true,
						ElementType: types.StringType,
						Description: `Not Null`,
						Validators: []validator.List{
							speakeasy_listvalidators.NotNull(),
						},
					},
				},
			},
			"filter_conditions": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"conditions": schema.ListNestedAttribute{
						Computed: true,
						Optional: true,
						NestedObject: schema.NestedAttributeObject{
							Validators: []validator.Object{
								speakeasy_objectvalidators.NotNull(),
							},
							Attributes: map[string]schema.Attribute{
								"field": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Dot-notation path to the field in the event payload (e.g. "entity.status", "entity.line_items"). Not Null`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
									},
								},
								"field_type": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Default:     stringdefault.StaticString(`string`),
									Description: `Type hint for the field (affects comparison logic). Default: "string"; must be one of ["string", "number", "boolean", "date", "datetime"]`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"string",
											"number",
											"boolean",
											"date",
											"datetime",
										),
									},
								},
								"is_array_field": schema.BoolAttribute{
									Computed:    true,
									Optional:    true,
									Default:     booldefault.StaticBool(false),
									Description: `Whether the target field is an array (repeatable). Default: false`,
								},
								"operation": schema.StringAttribute{
									Computed:    true,
									Optional:    true,
									Description: `Not Null; must be one of ["equals", "not_equals", "any_of", "none_of", "contains", "not_contains", "starts_with", "ends_with", "greater_than", "less_than", "greater_than_or_equals", "less_than_or_equals", "is_empty", "is_not_empty"]`,
									Validators: []validator.String{
										speakeasy_stringvalidators.NotNull(),
										stringvalidator.OneOf(
											"equals",
											"not_equals",
											"any_of",
											"none_of",
											"contains",
											"not_contains",
											"starts_with",
											"ends_with",
											"greater_than",
											"less_than",
											"greater_than_or_equals",
											"less_than_or_equals",
											"is_empty",
											"is_not_empty",
										),
									},
								},
								"values": schema.ListAttribute{
									Computed:    true,
									Optional:    true,
									ElementType: types.StringType,
									Description: `Values to compare against (not required for is_empty/is_not_empty)`,
								},
							},
						},
						Validators: []validator.List{
							listvalidator.SizeAtMost(10),
						},
					},
					"logical_operator": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Default:     stringdefault.StaticString(`AND`),
						Description: `Default: "AND"; must be one of ["AND", "OR"]`,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"AND",
								"OR",
							),
						},
					},
				},
				Description: `A group of conditions with a logical operator. Multiple conditions are AND-ed by default.`,
			},
			"http_method": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `must be one of ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"GET",
						"POST",
						"PUT",
						"PATCH",
						"DELETE",
						"OPTIONS",
						"HEAD",
					),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"jsonata_expression": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `JSONata expression to transform the payload`,
			},
			"manifest": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				Description: `Manifest ID used to create/update the webhook resource`,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"payload_configuration": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"custom_headers": schema.MapAttribute{
						Computed:    true,
						Optional:    true,
						ElementType: types.StringType,
						Description: `Object representing custom headers as key-value pairs.`,
					},
					"hydrate_entity": schema.BoolAttribute{
						Computed: true,
						Optional: true,
					},
					"include_activity": schema.BoolAttribute{
						Computed: true,
						Optional: true,
					},
					"include_changed_attributes": schema.BoolAttribute{
						Computed: true,
						Optional: true,
					},
					"include_relations": schema.BoolAttribute{
						Computed: true,
						Optional: true,
					},
				},
				Description: `Configuration for the webhook payload`,
			},
			"signing_secret": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: `Per-webhook signing secret following the Standard Webhooks specification.` + "\n" +
					`Only returned once during webhook creation. Use this secret to verify` + "\n" +
					`webhook signatures using the ` + "`" + `webhook-id` + "`" + `, ` + "`" + `webhook-timestamp` + "`" + `, and` + "\n" +
					`` + "`" + `webhook-signature` + "`" + ` headers.`,
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `must be one of ["active", "inactive", "incomplete"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"active",
						"inactive",
						"incomplete",
					),
				},
			},
			"url": schema.StringAttribute{
				Computed: true,
				Optional: true,
			},
		},
	}
}

func (r *WebhookResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *WebhookResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *WebhookResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedWebhookConfigInput(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Webhooks.CreateConfig(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 201 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.WebhookConfig != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedWebhookConfig(ctx, res.WebhookConfig)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *WebhookResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetConfigRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Webhooks.GetConfig(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.WebhookConfig != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedWebhookConfig(ctx, res.WebhookConfig)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *WebhookResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsUpdateConfigRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Webhooks.UpdateConfig(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.WebhookConfig != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedWebhookConfig(ctx, res.WebhookConfig)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *WebhookResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *WebhookResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsDeleteConfigRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Webhooks.DeleteConfig(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 204, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *WebhookResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
