// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type APIKeyConfig struct {
	KeyName  types.String `tfsdk:"key_name"`
	KeyValue types.String `tfsdk:"key_value"`
}
