// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BasicAuthConfig struct {
	Password         types.String `tfsdk:"password"`
	PasswordIsEnvVar types.Bool   `tfsdk:"password_is_env_var"`
	Username         types.String `tfsdk:"username"`
}
