// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type FileItem struct {
	Filename     types.String `tfsdk:"filename"`
	MimeType     types.String `tfsdk:"mime_type"`
	ReadableSize types.String `tfsdk:"readable_size"`
	S3ref        *S3Ref       `tfsdk:"s3ref"`
	SizeBytes    types.Int64  `tfsdk:"size_bytes"`
}
