// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Filter struct {
	KeyToFilter     types.String   `tfsdk:"key_to_filter"`
	SupportedValues []types.String `tfsdk:"supported_values"`
}
