// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type MultipartConfig struct {
	FileFieldName     types.String `tfsdk:"file_field_name"`
	MetadataFieldName types.String `tfsdk:"metadata_field_name"`
}
