// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PayloadConfiguration struct {
	CustomHeaders            map[string]types.String `tfsdk:"custom_headers"`
	HydrateEntity            types.Bool              `tfsdk:"hydrate_entity"`
	IncludeActivity          types.Bool              `tfsdk:"include_activity"`
	IncludeChangedAttributes types.Bool              `tfsdk:"include_changed_attributes"`
	IncludeRelations         types.Bool              `tfsdk:"include_relations"`
}
