// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SecureProxy struct {
	IntegrationID types.String `tfsdk:"integration_id"`
	UseCaseSlug   types.String `tfsdk:"use_case_slug"`
}
