// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type WebhookConditionGroup struct {
	Conditions      []WebhookCondition `tfsdk:"conditions"`
	LogicalOperator types.String       `tfsdk:"logical_operator"`
}
