// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type WebhookCondition struct {
	Field        types.String   `tfsdk:"field"`
	FieldType    types.String   `tfsdk:"field_type"`
	IsArrayField types.Bool     `tfsdk:"is_array_field"`
	Operation    types.String   `tfsdk:"operation"`
	Values       []types.String `tfsdk:"values"`
}
